# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BedFileReader__new <- function(famName_, bimName_, bedName_) {
    .Call(`_TLPRS_BedFileReader__new`, famName_, bimName_, bedName_)
}

rcpp_hello_world <- function() {
    .Call(`_TLPRS_rcpp_hello_world`)
}

